positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.17.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: log
    static_configs:
      - targets:
          - 172.17.0.1
        labels:
          job: log
          __path__: ./log/*.log